In [2]:
%pip install pandas

Requirement already satisfied: pandas in /Users/tiagocaravia-perry/coding-projects/MDSTFootballProject/.venv/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /Users/tiagocaravia-perry/coding-projects/MDSTFootballProject/.venv/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/tiagocaravia-perry/coding-projects/MDSTFootballProject/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/tiagocaravia-perry/coding-projects/MDSTFootballProject/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

df1 = pd.read_csv('2024DefenseData.csv')
df2 = pd.read_csv('2025DefenseData.csv')
df1['year'] = 2024
df2['year'] = 2025

print("File 1 Columns:", df1.columns.tolist())
print("File 2 Columns:", df2.columns.tolist())

File 1 Columns: ['Rk', 'Tm', 'G', 'PA', 'Yds', 'Ply', 'Y/P', 'TO', 'OFL', '1stD', 'Cmp', 'Att', 'Yds.1', 'TD', 'Int', 'NY/A', '1stD.1', 'Att.1', 'Yds.2', 'TD.1', 'Y/A', '1stD.2', 'Pen', 'Yds.3', '1stPy', 'Sc%', 'TO%', 'EXP', 'year']
File 2 Columns: ['Rk', 'Tm', 'G', 'PA', 'Yds', 'Ply', 'Y/P', 'TO', 'FL', '1stD', 'Cmp', 'Att', 'Yds.1', 'TD', 'Int', 'NY/A', '1stD.1', 'Att.1', 'Yds.2', 'TD.1', 'Y/A', '1stD.2', 'Pen', 'Yds.3', '1stPy', 'Sc%', 'TO%', 'EXP', '7.4', '8.3', '1', '1.1', 'PB,AP-1,AP MVP-1', 'year']

In [4]:
# Merge them side-by-side
combined_df = pd.concat([df1, df2], ignore_index=True)

# Preview the combined data right inside your notebook
combined_df.head()

,Rk,Tm,G,PA,Yds,Ply,Y/P,TO,OFL,1stD,...,Sc%,TO%,EXP,year,FL,7.4,8.3,1,1.1,"PB,AP-1,AP MVP-1"
0,1.0,Los Angeles Chargers,17.0,301,5514,1037.0,5.3,21.0,6.0,311.0,...,32.6,11.6,-11.72,2024,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Philadelphia Eagles,17.0,303,4732,999.0,4.7,26.0,13.0,293.0,...,31.6,14.1,47.74,2024,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Denver Broncos,17.0,311,5391,1093.0,4.9,25.0,10.0,327.0,...,31.6,12.4,57.45,2024,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Kansas City Chiefs,17.0,326,5451,1026.0,5.3,20.0,7.0,328.0,...,36.5,11.4,-55.29,2024,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Minnesota Vikings,17.0,332,5702,1078.0,5.3,33.0,9.0,325.0,...,31.6,16.6,38.73,2024,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
combined_df.to_csv('DefenseData.csv', index=False)

In [10]:
df3 = pd.read_csv('2024ReceivingData.csv')
df4 = pd.read_csv('2025ReceivingData.csv')
df3['year'] = 2024
df4['year'] = 2025

print("File 3 Columns:", df3.columns.tolist())
print("File 4 Columns:", df4.columns.tolist())

File 3 Columns: ['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'Tgt', 'Rec', 'Yds', 'Y/R', 'TD', '1D', 'Succ%', 'Lng', 'R/G', 'Y/G', 'Ctch%', 'Y/Tgt', 'Fmb', 'Awards', 'year']
File 4 Columns: ['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'Tgt', 'Rec', 'Yds', 'Y/R', 'TD', '1D', 'Succ%', 'Lng', 'R/G', 'Y/G', 'Ctch%', 'Y/Tgt', 'Fmb', 'Awards', 'year']

In [11]:
combined_receiving_df = pd.concat([df3, df4], ignore_index=True)
combined_receiving_df.to_csv('ReceivingData.csv', index=False)

In [12]:
df5 = pd.read_csv('2024RushingData.csv')
df6 = pd.read_csv('2025RushingData.csv')
df5['year'] = 2024
df6['year'] = 2025

combined_rushing_df = pd.concat([df5, df6], ignore_index=True)
combined_rushing_df.to_csv('RushingData.csv', index=False)

In [13]:
df7 = pd.read_csv('2024PassingData.csv')
df8 = pd.read_csv('2025PassingData.csv')
df7['year'] = 2024
df8['year'] = 2025

combined_passing_df = pd.concat([df7, df8], ignore_index=True)
combined_passing_df.to_csv('PassingData.csv', index=False)

In [23]:
dfReceive = pd.read_csv('ReceivingData.csv')
dfReceive.head()

,Rk,Player,Age,Team,Pos,G,GS,Tgt,Rec,Yds,...,1D,Succ%,Lng,R/G,Y/G,Ctch%,Y/Tgt,Fmb,Awards,year
0,1,Ja'Marr Chase,24,CIN,WR,17,16,175,127,1708,...,75,62.3,70.0,7.5,100.5,72.6,9.8,0,"PB,AP-1,AP MVP-8,AP OPoY-3",2024
1,2,Amon-Ra St. Brown,25,DET,WR,17,17,141,115,1263,...,80,70.2,66.0,6.8,74.3,81.6,9.0,1,"PB,AP-1,AP OPoY-11",2024
2,3,Brock Bowers,22,LVR,TE,17,16,153,112,1194,...,61,60.8,57.0,6.6,70.2,73.2,7.8,0,"PB,AP-1,AP ORoY-2",2024
3,4,Trey McBride,25,ARI,TE,16,16,147,111,1146,...,63,63.3,37.0,6.9,71.6,75.5,7.8,0,PB,2024
4,5,Malik Nabers,21,NYG,WR,15,13,170,109,1204,...,55,51.2,59.0,7.3,80.3,64.1,7.1,1,"PB,AP ORoY-5",2024

In [24]:
dfReceive = dfReceive.rename(columns={
    "Yds": "ReceiveYds",
    "TD": "ReceiveTD",
    "1D": "Receive1D",
    "Y/G": "ReceiveY/G"
})

dfReceive.head()

,Rk,Player,Age,Team,Pos,G,GS,Tgt,Rec,ReceiveYds,...,Receive1D,Succ%,Lng,R/G,ReceiveY/G,Ctch%,Y/Tgt,Fmb,Awards,year
0,1,Ja'Marr Chase,24,CIN,WR,17,16,175,127,1708,...,75,62.3,70.0,7.5,100.5,72.6,9.8,0,"PB,AP-1,AP MVP-8,AP OPoY-3",2024
1,2,Amon-Ra St. Brown,25,DET,WR,17,17,141,115,1263,...,80,70.2,66.0,6.8,74.3,81.6,9.0,1,"PB,AP-1,AP OPoY-11",2024
2,3,Brock Bowers,22,LVR,TE,17,16,153,112,1194,...,61,60.8,57.0,6.6,70.2,73.2,7.8,0,"PB,AP-1,AP ORoY-2",2024
3,4,Trey McBride,25,ARI,TE,16,16,147,111,1146,...,63,63.3,37.0,6.9,71.6,75.5,7.8,0,PB,2024
4,5,Malik Nabers,21,NYG,WR,15,13,170,109,1204,...,55,51.2,59.0,7.3,80.3,64.1,7.1,1,"PB,AP ORoY-5",2024

In [18]:
dfRush = pd.read_csv('RushingData.csv')
dfRush = dfRush.rename(columns={
    "Yds": "RushYds",
    "TD": "RushTD",
    "1D": "Rush1D",
    "Att" : "RushAtt",
    "Y/G": "RushY/G"
})

dfRush.head()

,Rk,Player,Age,Team,Pos,G,GS,RushAtt,RushYds,RushTD,Rush1D,Succ%,Lng,Y/A,RushY/G,A/G,Fmb,Awards,year
0,1,Saquon Barkley,27,PHI,RB,16,16,345,2005,13,99,52.5,72.0,5.8,125.3,21.6,2,"PB,AP-1,AP MVP-3,AP OPoY-1,AP CPoY-14",2024
1,2,Derrick Henry,30,BAL,RB,17,17,325,1921,16,106,58.8,87.0,5.9,113.0,19.1,3,"PB,AP-2,AP OPoY-4",2024
2,3,Kyren Williams,24,LAR,RB,16,16,316,1299,14,92,50.9,30.0,4.1,81.2,19.8,5,AP OPoY-11,2024
3,4,Bijan Robinson,22,ATL,RB,17,17,304,1456,14,82,60.2,37.0,4.8,85.6,17.9,1,PB,2024
4,5,Jonathan Taylor,25,IND,RB,14,13,303,1431,11,71,45.9,70.0,4.7,102.2,21.6,4,"PB,AP CPoY-19",2024

In [19]:
dfPass = pd.read_csv('PassingData.csv')
dfPass = dfPass.rename(columns={
    "Yds": "PassYds",
    "TD": "PassTD",
    "1D": "Pass1D",
    "Att" : "PassAtt",
    "Y/G": "PassY/G"
})

dfPass.head()

,Rk,Player,Age,Team,Pos,G,GS,QBrec,Cmp,PassAtt,...,Sk,Yds.1,Sk%,NY/A,ANY/A,4QC,GWD,Awards,year,Yds_Sacked
0,1.0,Joe Burrow,28.0,CIN,QB,17.0,17.0,9-8-2000,460.0,652.0,...,48.0,278.0,6.86,6.6,7.3,1.0,2.0,"PB,AP MVP-4,AP OPoY-5,AP CPoY-1",2024,NaN
1,2.0,Jared Goff,30.0,DET,QB,17.0,17.0,15-2-0,390.0,539.0,...,31.0,234.0,5.44,7.7,8.1,4.0,4.0,"PB,AP MVP-5,AP OPoY-9",2024,NaN
2,3.0,Baker Mayfield,29.0,TAM,QB,17.0,17.0,10-7-2000,407.0,570.0,...,40.0,248.0,6.56,7.0,7.1,2.0,2.0,"PB,AP MVP-11,AP OPoY-11",2024,NaN
3,4.0,Geno Smith,34.0,SEA,QB,17.0,17.0,10-7-2000,407.0,578.0,...,50.0,338.0,7.96,6.3,5.9,4.0,4.0,NaN,2024,NaN
4,5.0,Sam Darnold,27.0,MIN,QB,17.0,17.0,14-3-0,361.0,545.0,...,48.0,335.0,8.09,6.7,7.0,3.0,5.0,"PB,AP MVP-10,AP CPoY-3",2024,NaN

In [26]:
FantasyDF = pd.concat([dfRush, dfPass, dfReceive], ignore_index=True)
FantasyDF.head()
FantasyDF.to_csv('FantasyData.csv', index=False)